name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  neeraj: 
    name: neeraj_job
    runs-on: ubuntu-latest
    steps: 
    - name: nmae
      run: ls
    
  push_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: work/not 
      run: |
        echo "running pwd"
        pwd
        echo "running ls"
        ls -l
    - name: my_server_login
      run: |
        echo "login into server "
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@54.82.9.251
        echo "going to repo"
        sudo su
        cd /var/www/html/test_rep
        echo "pwd"
        pwd
        echo "pull"
        git pull origin main
        
     

    # - name: Copy files to EC2
    #   run: 
    #     echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
    #     chmod 600 deploy_key.pem
    #     scp -i deploy_key.pem -r ./ ec2-user@your-ec2-ip:/path/to/app/
    #   env:
    #     DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
