name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  neeraj: 
    name: neeraj_job
    runs-on: ubuntu-latest
    steps: 
    - name: nmae
      run: ls
    
  push_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: work/not 
      run: |
        echo "running pwd"
        pwd
        echo "running ls"
        ls -l
    - name: my_server_login
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > token_key.pem
        chmod 400 token_key.pem
        echo "login into server "
        ssh -T -o StrictHostKeyChecking=no  -i token_key.pem ec2-user@54.91.9.147 << 'EOF'
        echo "who am i "
        whoami
        echo "pwd"
        pwd
        echo "going to repo"
        sudo su
        echo "pwd"
        pwd
        echo "cd to repo dir under apache www"
        cd /home/ec2-user/repos/test_rep
        echo "pwd"
        pwd
        
        echo "Setting Git safe directory"
        git config --global --add safe.directory /home/ec2-user/repos/test_rep
        echo "Setting up SSH agent for git"
        eval $(ssh-agent -s)
        ssh-add /home/ec2-user/.ssh/id_rsa   
        
        echo "pull"
        sudo git checkout -f main
        git pull origin main
        echo "restart docker-compose"
        # sudo systemctl restart apache2
        sudo docker-compose down -v
        sudo docker-compose up -d
        echo "index cat contens"
        cat /home/ec2-user/repos/test_rep/app.py
        exit
        exit
        EOF

        # Clean up
        rm -f token_key.pem

        echo "Deployment complete"
        

     

    # - name: Copy files to EC2
    #   run: 
    #     echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
    #     chmod 600 deploy_key.pem
    #     scp -i deploy_key.pem -r ./ ec2-user@your-ec2-ip:/path/to/app/
    #   env:
    #     DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
