name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  neeraj: 
    name: neeraj_job
    runs-on: ubuntu-latest
    
  push_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: work/not 
      run: 
        pwd
        ls -l
        
     

    # - name: Copy files to EC2
    #   run: 
    #     echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
    #     chmod 600 deploy_key.pem
    #     scp -i deploy_key.pem -r ./ ec2-user@your-ec2-ip:/path/to/app/
    #   env:
    #     DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
